### ISSUE TITLE
Add Swipe to Refresh - Latest episodes list is not loading

### ISSUE THREAD

**Issue by tobiasorth1** [SoftwareEngineeringDaily/SEDaily-Android#54]
## Device Details
- Device Name: Xiaomi Redmi Pro 4
- Android Version: 7.0
- App Version: 1.1

## Steps to Reproduce:
1. Open app
2. Got to tab "Just for you" or "Greatest Hits"
3. Go back to tab "Latest"
4. No episode list is loading

**Comment by TheHollidayInn** [comment]
This should be fixed now. Can you check? It is an issue with our dataminer getting stuck

**Comment by tobiasorth1** [comment]
Problem still exists.
Doesn't display anything for "ALL". When I swipe right, it seems that there is a tab between "ALL" and "BUSINESS [...]" as the red line floats in between. When I swipe to "Blockchain" content is loaded.
App also crashes when I swipe to the right, wait, swipe right, wait, swipe. Maybe synchronization issues?
It also appears that the content for each category tab is fetched from the server - building the content on the UI takes quite some time.

**Comment by TheHollidayInn** [comment]
Gotcha. Thanks for helping me debug!

We do have to load from the server, but the dev build has some performance improvements. I also think I have a solution that will fix the swipe crash. 

But for fetching the most recent content, if you swipe away and close the app completely, then open the app does the content load?

**Comment by tobiasorth1** [comment]
Starting fresh works for me. Just the limitations I've posted exist.

**Comment by TheHollidayInn** [comment]
Thanks! I leave this open so we can fix.
